// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceWorker.Infrastructure.Data;

#nullable disable

namespace ServiceWorker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ServiceWorkerDbContext))]
    [Migration("20260624141036_CreateUsersTable")]
    partial class CreateUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceWorker.Domain.Entities.ScheduleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("RecommendedProduct")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommended_product");

                    b.Property<int>("ScheduleDay")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_day");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<string>("UsageInstruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usage_instruction");

                    b.HasKey("Id")
                        .HasName("pk_schedule_items");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_schedule_items_schedule_id");

                    b.ToTable("schedule_items", (string)null);
                });

            modelBuilder.Entity("ServiceWorker.Domain.Entities.TreatmentSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("ServiceWorker.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("guid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<string>("LPQuizDiagnosticJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("lp_quiz_diagnostic_json");

                    b.Property<bool>("LgpdConsentGranted")
                        .HasColumnType("boolean")
                        .HasColumnName("lgpd_consent_granted");

                    b.Property<DateTime>("LgpdConsentTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lgpd_consent_timestamp");

                    b.Property<string>("PixCustomerId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pix_customer_id");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("subscription_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Guid")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ServiceWorker.Infrastructure.PersistancyEntities.SkinAnalysisPersistancyEntity", b =>
                {
                    b.Property<Guid>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions_json");

                    b.Property<float>("OverallHealthScore")
                        .HasColumnType("real")
                        .HasColumnName("overall_health_score");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations_json");

                    b.HasKey("AnalysisId")
                        .HasName("pk_skin_analyses");

                    b.ToTable("skin_analyses", (string)null);
                });

            modelBuilder.Entity("ServiceWorker.Domain.Entities.ScheduleItem", b =>
                {
                    b.HasOne("ServiceWorker.Domain.Entities.TreatmentSchedule", null)
                        .WithMany("Items")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_schedule_items_schedules_schedule_id");
                });

            modelBuilder.Entity("ServiceWorker.Domain.Entities.TreatmentSchedule", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
