// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceWorker.Infrastructure.Data;

#nullable disable

namespace ServiceWorker.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ServiceWorkerDbContext))]
    [Migration("20260618030428_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceWorker.Domain.Entities.ScheduleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("RecommendedProduct")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommended_product");

                    b.Property<int>("ScheduleDay")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_day");

                    b.Property<Guid?>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<string>("UsageInstruction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usage_instruction");

                    b.HasKey("Id")
                        .HasName("pk_schedule_items");

                    b.HasIndex("ScheduleId")
                        .HasDatabaseName("ix_schedule_items_schedule_id");

                    b.ToTable("schedule_items", (string)null);
                });

            modelBuilder.Entity("ServiceWorker.Domain.Entities.TreatmentSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("ServiceWorker.Infrastructure.PersistancyEntities.SkinAnalysisPersistancyEntity", b =>
                {
                    b.Property<Guid>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_id");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("analyzed_at");

                    b.Property<string>("ConditionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("conditions_json");

                    b.Property<float>("OverallHealthScore")
                        .HasColumnType("real")
                        .HasColumnName("overall_health_score");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<string>("RecommendationsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations_json");

                    b.HasKey("AnalysisId")
                        .HasName("pk_skin_analyses");

                    b.ToTable("skin_analyses", (string)null);
                });

            modelBuilder.Entity("ServiceWorker.Domain.Entities.ScheduleItem", b =>
                {
                    b.HasOne("ServiceWorker.Domain.Entities.TreatmentSchedule", null)
                        .WithMany("Items")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_schedule_items_schedules_schedule_id");
                });

            modelBuilder.Entity("ServiceWorker.Domain.Entities.TreatmentSchedule", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
